{{- if .Values.workflow.rbac.create -}}
{{- $controllers := .Values.controllers | default (dict (include "argo-workflows.namespace" .) .Values.controller) }}
{{- $workflowNamespaces := default list }}
{{- range $config := values $controllers }}
{{- $controller := deepCopy $.Values.controller | merge $config }}
{{- $workflowNamespaces = concat $workflowNamespaces $controller.workflowNamespaces }}
{{- end }}
{{- range $ns := $workflowNamespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "argo-workflows.fullname" $ }}-workflow
  labels:
    {{- include "argo-workflows.labels" (dict "context" $ "component" $.Values.controller.name "name" $.Values.controller.name) | nindent 4 }}
    {{- with $ns }}
  namespace: {{ . }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "argo-workflows.fullname" $ }}-workflow
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.workflow.serviceAccount.name }}
    {{- with $ns }}
    namespace: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
