{{- if .Values.workflow.serviceAccount.create -}}
{{- $controllers := .Values.controllers | default (dict (include "argo-workflows.namespace" .) .Values.controller) }}
{{- $workflowNamespaces := default list }}
{{- range $config := values $controllers }}
{{- $controller := deepCopy $.Values.controller | merge $config }}
{{- $workflowNamespaces = concat $workflowNamespaces $controller.workflowNamespaces }}
{{- end }}
{{- range $ns := $workflowNamespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.workflow.serviceAccount.name }}
  labels:
    {{- include "argo-workflows.labels" (dict "context" $ "component" $.Values.controller.name "name" $.Values.controller.name) | nindent 4 }}
  {{- with $.Values.workflow.serviceAccount.labels  }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- with $ns }}
  namespace: {{ . }}
    {{- end }}
    {{- with $.Values.workflow.serviceAccount.annotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.workflow.serviceAccount.pullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 2 }}
  {{- end }}
  {{- end }}
{{- end }}
